'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

const ACTION_SCHEMA = 'action_schema';
const ATTRIBUTION = 'attribution';
const DASHBOARD = 'dashboards';
const DYNAMIC_FIELD = 'dynamic_fields';
const FOLDER = 'folders';
const JOURNEY = 'journeys';
const PEOPLE = 'people';
const PERMISSION = 'permissions';
const REPORT = 'reports';
const RETENTION = 'retention';
const SCHEDULED_BATCH = 'scheduledbatches';
const SCHEDULED_JOB = 'scheduledjobs';
const SCHEDULED_REPORT = 'scheduledreports';
const SCHEDULED_TASK = 'scheduledtasks';
const SCHEMA_GROUP = 'schema_groups';
const SEGMENT = 'segments';
const TAG = 'tags';
const TOP_N = 'top_n';
const TRENDS = 'trends';
const TRIGGER = 'triggers';
const VISITOR_SCHEMA = 'visitor_schema';
const WIDGET = 'widgets';

exports.ACTION_SCHEMA = ACTION_SCHEMA;
exports.ATTRIBUTION = ATTRIBUTION;
exports.DASHBOARD = DASHBOARD;
exports.DYNAMIC_FIELD = DYNAMIC_FIELD;
exports.FOLDER = FOLDER;
exports.JOURNEY = JOURNEY;
exports.PEOPLE = PEOPLE;
exports.PERMISSION = PERMISSION;
exports.REPORT = REPORT;
exports.RETENTION = RETENTION;
exports.SCHEDULED_BATCH = SCHEDULED_BATCH;
exports.SCHEDULED_JOB = SCHEDULED_JOB;
exports.SCHEDULED_REPORT = SCHEDULED_REPORT;
exports.SCHEDULED_TASK = SCHEDULED_TASK;
exports.SCHEMA_GROUP = SCHEMA_GROUP;
exports.SEGMENT = SEGMENT;
exports.TAG = TAG;
exports.TOP_N = TOP_N;
exports.TRENDS = TRENDS;
exports.TRIGGER = TRIGGER;
exports.VISITOR_SCHEMA = VISITOR_SCHEMA;
exports.WIDGET = WIDGET;